run:
  timeout: 3m
  skip-files: []
  skip-dirs: []

linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 18 # TODO must be changed to 12 or 15
  goconst:
    min-len: 3
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: 120
    statements: 40

linters:
  enable-all: true
  disable:
    - golint # deprecated
    - maligned # deprecated
    - interfacer # deprecated
    - scopelint # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - testpackage
    - tparallel
    - paralleltest
    - gomnd
    - goerr113
    - nlreturn
    - exhaustive
    - exhaustivestruct
    - noctx
    - wrapcheck
    - wsl
    - forbidigo
    - nestif
    - varnamelen
    - nilnil
    - gocognit # TODO must be enable

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: [
    "should have a package comment",
    "don't use MixedCaps in package name", # TODO must be fixed
    "ST1003: should not use MixedCaps in package name", # TODO must be fixed
  ]
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot
        - gosec
